apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongoapi
spec:
  selector:
    matchLabels:
      app: mongoapi
  template:
    metadata:
      labels:
        app: mongoapi
    spec:
      containers:
      - name: mongoapi
        image: docker.io/mmadert9s/mongoapi:0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mongoapi
spec:
  selector:
    app: mongoapi
  ports:
  - port: 8080
    targetPort: 8080
